version: "3.8"
services:
  app:
    build:
      context: app
      dockerfile: ${MODE}.Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/next.config.ts:/app/next.config.ts
      - ./app/components.json:/app/components.json
      - ./app/package.json:/app/package.json
      - ./app/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/tsconfig.app.json:/app/tsconfig.app.json
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/.env.local:/app/.env.local
      - node_modules:/app/node_modules
      - build:/app/.next
    networks:
      - posture-correction-app-request
    tty: true

  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - app
    networks:
      - posture-correction-app-request
    extra_hosts:
      - "backend-host-1:${BACKEND_HOST_1}"
      - "backend-host-2:${BACKEND_HOST_2}"
    env_file:
      - .env
    tty: true

volumes:
  node_modules:
  build:

networks:
  posture-correction-app-request:
    driver: bridge
