version: "3.8"
services:
  app:
    build:
      context: app
      dockerfile: ${MODE}.Dockerfile
    ports:
      - "7001:3000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    networks:
      - posture-correction-app-request
    extra_hosts:
      - "backend-host-1:${BACKEND_HOST_1}"
      - "backend-host-2:${BACKEND_HOST_2}"
    tty: true

volumes:
  node_modules:

networks:
  posture-correction-app-request:
    driver: bridge
